### ISSUE TITLE
Issue resolving meta argument context

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk3#213]
I'm either doing something very wrong or this is potentially an issue.

Minimal reproduction example:
```logtalk
% closure.lgt
:- object(state).
    :- public([run/2, return//1]).

    :- meta_predicate(run(::,*)). % or (2,*) or (*,*)

    return(X, _, [S]) :- S = X.

    run(X, S) :- phrase(X, [], S).

:- end_object.

% tests.lgt
:- object(test, extends(state)).
    :- public([t//0, test_bad/0, test_good/0]).

    t --> ::return(true).

    test_bad :-
        ::run(t, S),
        writeln(S).

    test_good :-
        ::run(test::t, S),
        writeln(S).

:- end_object.

% loader.lgt
:- initialization (
    logtalk_load([closure, tests])
).
```

Seems like both tests should be working.

```logtalk
?- test::test_good.
[true]
true.

[debug]  ?- test::test_bad.
ERROR: Unknown procedure: '$state#0.t#2'/3
ERROR: In:
ERROR:   [17] '$state#0.t#2'([],_348,c(state,state,r(test,test,...,[])))
ERROR:   [16] '$lgt_phrase'(t,[],_396,c(state,state,r(test,test,...,[]))) at /usr/local/share/logtalk/core/core.pl:5335
ERROR:   [15] '$state#0.run#2'(t,_442,c(state,state,r(test,test,...,[]))) at /Users/orbital/work/cl/onto/tmp/logtalk-closure-fail-example/.lgt_tmp/closure_10473623_98311_lgt.pl:12
ERROR:   [14] '$lgt_send_to_self_'(test,run(t,_496),c(test,test,r(user,test,[],[])))2-nd clause of ::/1 <no source>
ERROR:   [13] '$test#0.test_bad#0'(c(test,test,r(user,test,[],[]))) at /Users/orbital/work/cl/onto/tmp/logtalk-closure-fail-example/.lgt_tmp/tests_10473623_98311_lgt.pl:16
ERROR:   [12] '$lgt_send_to_obj_ne_'(test,test_bad,c(user,user,r(user,_598,[],[])))1-st clause of ::/2 (event transparent) <no source>
```

Also, `::run(::t, S)` works too. AFAICT from docs and examples I should be able to pass a local `t` to meta-predicate `run` without fully qualifying it.

A more complex example involving meta-arguments to a non-terminal operator:

```logtalk
:- object(state).
    :- public([run/2, return//1, peek//1, (<>)//2]).

    :- op(950, xfy, <>).

    :- meta_predicate(run(::,*)).
    :- meta_non_terminal(<>(::,::)).

    return(X, _, [S]) :- S = X.
    peek(X, [X], [X]).

    <>(A,B) --> A, call(peek, T),
        (   { T==true } -> { true }
        ;   B
        ).

    run(X, S) :- phrase(X, [], S).

:- end_object.


:- object(test, extends(state)).
    :- public([t//0, g//0, test_bad/0, test_op1/0, test_op2/0]).
    :- uses(state, [(<>)//2]).

    :- op(950, xfy, <>).

    t --> ::return(true).
    g --> t <> t.

    test_op1 :-
        ::run(::t <> ::t, S),
        writeln(S).

    test_op2 :-
        ::run(::g, S),
        writeln(S).

:- end_object.
```

`test_op1` works fine, `test_op2` will not work.

```logtalk
?- test::test_op1.
[true]
true.

[debug]  ?- test::test_op2.
ERROR: Unknown procedure: '$state#0.t#2'/3
ERROR: In:
ERROR:   [22] '$state#0.t#2'([],_498,c(state,state,r(test,state,...,[])))
ERROR:   [21] '$lgt_phrase'(t,[],_546,c(state,state,r(test,state,...,[]))) at /usr/local/share/logtalk/core/core.pl:5335
```

Pretty sure I've tried every possible combination of 0/*/:: in meta_ declarations and of qualifying `g` and `t`. Cannot seem to figure out the pattern to meta-argument behavior when arguments are non-terminals. :(

Logtalk 3.80.0-b01

**Comment by unthingable** [comment]
The operator example is a simplified real use case (that was working fine in plain Prolog, with `:- meta_predicate <>(//,//,*,*).` and nothing at all for `run`), a large remaining blocker to the Logtalk port.

**Comment by pmoura** [comment]
Indeed both tests should give the same result. Thanks for reporting and the handy simple example to reproduce this embarrassing bug. Fixed in 18ea2f93b79d5dc8895868030afbd30c1939156f.

The correct directive in this case is:

```logtalk
:- meta_predicate(run(2, *)).
```

**Comment by unthingable** [comment]
Yay! The above test now works, thank you. Btw, installing latest git version still says `Installing Logtalk 3.80.0-b01`.

Unfortunately for me, my real test is still having these issues, trying to figure out why. Does it make a difference whether `run` is declared public in the object or in the protocol implemented by this object?

**Comment by pmoura** [comment]
Meta-predicate directives are not inherited (to allow independent entity compilation), they must be repeated in descendent entities providing definitions for the meta-predicates. Could that be the issue?

P.S. Logtalk 3.80.0 may be released as soon as next week.

**Comment by unthingable** [comment]
Ok, the issue was that `run` was declared public in a protocol, `state` object with meta-predicate directive implemented said protocol but didn't redeclare public predicates. Moving `:- public` declarations to the object and dropping the protocol fixed it. Thanks!

P.S. Got it, had my wires crossed and thought 80 came before 79 :-D

**Comment by pmoura** [comment]
That doesn't sound correct. Scope directives are always inherited. Thus, in your case, `run/2` would be declared both public and meta-predicate in the protocol and only the meta-predicate directive would be repeated in the object implementing the predicate.

**Comment by unthingable** [comment]
To clarify, the protocol didn't have the meta-predicate directive.
